name: ARM Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'storage_template.json'
      - 'storage_parameters.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: myResourceGroup
          template: ./storage_template.json
          parameters: ./storage_parameters.json
          deploymentName: github-action-deploy
